### ISSUE TITLE
Error creating vaadin project from scratch

### ISSUE THREAD

**Issue by jmiguelr** [grails-guides/vaadin-grails#5]
In the guide, trying to create another project from scratch, executing the command 

`#grails create-app demo --profile me.przepiora.vaadin-grails:web-vaadin8:0.3`

I get to following error:

`Error Error occurred running Grails CLI: One or more required features were not found on the classpath. Required features: [gsp, asset-pipeline, gradle-vaadin-plugin] (Use --stacktrace to see the full trace)`

Not sure if there is some fault from my side.  

Thank you!

**Comment by jeffscottbrown** [comment]
I think that error is probably happening because you are using Grails 3.2.x.  The command above will work with Grails 3.3.x.  For 3.2.x you want version 8.0.2 of the profile.

**Comment by jmiguelr** [comment]
Right!.  It was my fault.  I have 3.2.9 as default Grails version on shell but after change to 3.3.1 with sdkman the projects it's created ok. 

Thank you very much, @jeffbrown !
